In [11]:
import heapq

# Define uma classe para representar o tabuleiro do 8-Puzzle
class PuzzleBoard:
    def __init__(self, state, parent=None, move=None):
        self.state = state  # Estado atual do tabuleiro
        self.parent = parent  # Tabuleiro pai
        self.move = move  # Movimento que levou a este estado
        self.cost = 0  # Custo total (g + h)
        self.calculate_cost()

    def calculate_cost(self):
        # Calcula o custo g (movimentos feitos) e h (heurística)
        self.cost = self.calculate_g() + self.calculate_h()

    def calculate_g(self):
        # Cálculo do custo g (número de movimentos feitos)
        if self.parent is None:
            return 0
        return self.parent.calculate_g() + 1

    def calculate_h(self):
        # Cálculo da heurística (neste caso, número de peças fora do lugar)
        goal_state = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]
        h = 0
        for i in range(3):
            for j in range(3):
                if self.state[i][j] != goal_state[i][j]:
                    h += 1
        return h

    def __lt__(self, other):
        return self.cost < other.cost

    def __eq__(self, other):
        return self.state == other.state

    def __hash__(self):
        return hash(str(self.state))

    def get_possible_moves(self):
        # Obtém todos os movimentos possíveis a partir deste estado
        moves = []
        zero_row, zero_col = self.find_zero()
        if zero_row > 0:
            moves.append("Up")
        if zero_row < 2:
            moves.append("Down")
        if zero_col > 0:
            moves.append("Left")
        if zero_col < 2:
            moves.append("Right")
        return moves

    def find_zero(self):
        # Encontra a posição do zero no tabuleiro
        for i in range(3):
            for j in range(3):
                if self.state[i][j] == 0:
                    return i, j

    def make_move(self, move):
        # Faz um movimento no tabuleiro
        zero_row, zero_col = self.find_zero()
        new_state = [list(row) for row in self.state]
        if move == "Up":
            new_state[zero_row][zero_col], new_state[zero_row - 1][zero_col] = (
                new_state[zero_row - 1][zero_col],
                new_state[zero_row][zero_col],
            )
        elif move == "Down":
            new_state[zero_row][zero_col], new_state[zero_row + 1][zero_col] = (
                new_state[zero_row + 1][zero_col],
                new_state[zero_row][zero_col],
            )
        elif move == "Left":
            new_state[zero_row][zero_col], new_state[zero_row][zero_col - 1] = (
                new_state[zero_row][zero_col - 1],
                new_state[zero_row][zero_col],
            )
        elif move == "Right":
            new_state[zero_row][zero_col], new_state[zero_row][zero_col + 1] = (
                new_state[zero_row][zero_col + 1],
                new_state[zero_row][zero_col],
            )
        return PuzzleBoard(new_state, parent=self, move=move)

    def is_goal(self):
        # Verifica se o estado atual é o estado final
        goal_state = [[1, 2, 3], [4, 5, 6], [7, 8, 0]]
        return self.state == goal_state

    def get_path(self):
        # Obtém o caminho do estado inicial ao estado final
        path = []
        current_state = self
        while current_state is not None:
            path.append((current_state.state, current_state.move))
            current_state = current_state.parent
        path.reverse()
        return path

# Função para resolver o 8-Puzzle usando o algoritmo A*
def solve_8_puzzle(initial_state):
    open_list = []
    closed_set = set()
    initial_board = PuzzleBoard(initial_state)
    heapq.heappush(open_list, initial_board)

    while open_list:
        current_board = heapq.heappop(open_list)

        if current_board.is_goal():
            return current_board.get_path()

        closed_set.add(current_board)

        for move in current_board.get_possible_moves():
            new_board = current_board.make_move(move)
            if new_board not in closed_set:
                heapq.heappush(open_list, new_board)

    return None

# Função para imprimir o caminho do estado inicial ao estado final
def print_solution(path):
    for i, (state, move) in enumerate(path):
        print(f"Step {i + 1}:")
        for row in state:
            print(row)
        if move:
            print(f"Move: {move}\n")

if __name__ == "__main__":
    initial_state = [[5, 3, 2], [6, 1, 8], [7, 0, 4]]
    solution_path = solve_8_puzzle(initial_state)
    if solution_path:
        print_solution(solution_path)
    else:
        print("Não foi possível encontrar uma solução.")

Initial State: 
[[7 2 8]
 [1 3 5]
 [0 4 6]]


ValueError: ignored

In [13]:
import numpy as np

# Define uma classe para representar o tabuleiro do 8-Puzzle
class PuzzleBoard:
    def __init__(self, state, parent=None, move=None):
        self.state = state  # Estado atual do tabuleiro
        self.parent = parent  # Tabuleiro pai
        self.move = move  # Movimento que levou a este estado
        self.cost = 0  # Custo total (g + h)
        self.calculate_cost()

    def calculate_cost(self):
        # Calcula o custo g (movimentos feitos) e h (heurística)
        self.cost = self.calculate_g() + self.calculate_h()

    def calculate_g(self):
        # Cálculo do custo g (número de movimentos feitos)
        if self.parent is None:
            return 0
        return self.parent.calculate_g() + 1

    def calculate_h(self):
        # Cálculo da heurística (neste caso, número de peças fora do lugar)
        goal_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        h = np.sum(self.state != goal_state)
        return h

    def __lt__(self, other):
        return self.cost < other.cost

    def __eq__(self, other):
        return np.array_equal(self.state, other.state)

    def __hash__(self):
        return hash(str(self.state))

    def get_possible_moves(self):
        # Obtém todos os movimentos possíveis a partir deste estado
        moves = []
        zero_row, zero_col = np.where(self.state == 0)
        zero_row, zero_col = zero_row[0], zero_col[0]
        if zero_row > 0:
            moves.append("Up")
        if zero_row < 2:
            moves.append("Down")
        if zero_col > 0:
            moves.append("Left")
        if zero_col < 2:
            moves.append("Right")
        return moves

    def make_move(self, move):
        # Faz um movimento no tabuleiro
        zero_row, zero_col = np.where(self.state == 0)
        zero_row, zero_col = zero_row[0], zero_col[0]
        new_state = self.state.copy()
        if move == "Up":
            new_state[zero_row, zero_col], new_state[zero_row - 1, zero_col] = (
                new_state[zero_row - 1, zero_col],
                new_state[zero_row, zero_col],
            )
        elif move == "Down":
            new_state[zero_row, zero_col], new_state[zero_row + 1, zero_col] = (
                new_state[zero_row + 1, zero_col],
                new_state[zero_row, zero_col],
            )
        elif move == "Left":
            new_state[zero_row, zero_col], new_state[zero_row, zero_col - 1] = (
                new_state[zero_row, zero_col - 1],
                new_state[zero_row, zero_col],
            )
        elif move == "Right":
            new_state[zero_row, zero_col], new_state[zero_row, zero_col + 1] = (
                new_state[zero_row, zero_col + 1],
                new_state[zero_row, zero_col],
            )
        return PuzzleBoard(new_state, parent=self, move=move)

    def is_goal(self):
        # Verifica se o estado atual é o estado final
        goal_state = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
        return np.array_equal(self.state, goal_state)

    def get_path(self):
        # Obtém o caminho do estado inicial ao estado final
        path = []
        current_state = self
        while current_state is not None:
            path.append((current_state.state, current_state.move))
            current_state = current_state.parent
        path.reverse()
        return path

# Função para resolver o 8-Puzzle usando o algoritmo A*
def solve_8_puzzle(initial_state):
    open_list = []
    closed_set = set()
    initial_board = PuzzleBoard(initial_state)
    open_list.append(initial_board)

    while open_list:
        current_board = open_list.pop(0)

        if current_board.is_goal():
            return current_board.get_path()

        closed_set.add(current_board)

        for move in current_board.get_possible_moves():
            new_board = current_board.make_move(move)
            if new_board not in closed_set:
                open_list.append(new_board)
                open_list.sort(key=lambda x: x.cost)

    return None

# Função para imprimir o caminho do estado inicial ao estado final
def print_solution(path):
    for i, (state, move) in enumerate(path):
        print(f"Step {i + 1}:")
        print(state)
        if move:
            print(f"Move: {move}\n")

if __name__ == "__main__":
    # Gere um estado inicial aleatório
    initial_state = np.arange(9)
    np.random.shuffle(initial_state)
    initial_state = initial_state.reshape(3, 3)
    print("Initial State: ")
    print(initial_state)
    solution_path = solve_8_puzzle(initial_state)
    if solution_path:
        print_solution(solution_path)
    else:
        print("Não foi possível encontrar uma solução.")

Initial State: 
[[2 5 0]
 [4 6 3]
 [8 7 1]]
Step 1:
[[2 5 0]
 [4 6 3]
 [8 7 1]]
Step 2:
[[2 5 3]
 [4 6 0]
 [8 7 1]]
Move: Down

Step 3:
[[2 5 3]
 [4 6 1]
 [8 7 0]]
Move: Down

Step 4:
[[2 5 3]
 [4 6 1]
 [8 0 7]]
Move: Left

Step 5:
[[2 5 3]
 [4 0 1]
 [8 6 7]]
Move: Up

Step 6:
[[2 5 3]
 [4 1 0]
 [8 6 7]]
Move: Right

Step 7:
[[2 5 3]
 [4 1 7]
 [8 6 0]]
Move: Down

Step 8:
[[2 5 3]
 [4 1 7]
 [8 0 6]]
Move: Left

Step 9:
[[2 5 3]
 [4 1 7]
 [0 8 6]]
Move: Left

Step 10:
[[2 5 3]
 [0 1 7]
 [4 8 6]]
Move: Up

Step 11:
[[2 5 3]
 [1 0 7]
 [4 8 6]]
Move: Right

Step 12:
[[2 5 3]
 [1 7 0]
 [4 8 6]]
Move: Right

Step 13:
[[2 5 3]
 [1 7 6]
 [4 8 0]]
Move: Down

Step 14:
[[2 5 3]
 [1 7 6]
 [4 0 8]]
Move: Left

Step 15:
[[2 5 3]
 [1 0 6]
 [4 7 8]]
Move: Up

Step 16:
[[2 0 3]
 [1 5 6]
 [4 7 8]]
Move: Up

Step 17:
[[0 2 3]
 [1 5 6]
 [4 7 8]]
Move: Left

Step 18:
[[1 2 3]
 [0 5 6]
 [4 7 8]]
Move: Down

Step 19:
[[1 2 3]
 [4 5 6]
 [0 7 8]]
Move: Down

Step 20:
[[1 2 3]
 [4 5 6]
 [7 0 8]]
Move: Right

S

In [ ]:
#Código para achar os movimentos
import numpy as np
def buscaCoordenadas(tabela):
  # pegar as coordenadas do 0 (arrays)
  linha_zero,coluna_zero = np.where(tabela == 0)
  return linha_zero[0],coluna_zero[0]

def movimentosPossiveis(tabela):
  movimentos_permitidos = []
  linha_zero, coluna_zero = buscaCoordenadas(tabela)
  #se não é a primeira linha, pode subir
  if linha_zero > 0:
      movimentos_permitidos.append((0,1))
  #se não é a última linha, pode descer
  if linha_zero < 2:
      movimentos_permitidos.append((0,-1))
  #se não é a primeira coluna, pode ir para a esquerda
  if coluna_zero > 0:
      movimentos_permitidos.append((-1,0))
  #se não é a última coluna, pode ir para a direita
  if coluna_zero < 2:
      movimentos_permitidos.append((1,0))
  return movimentos_permitidos

print(movimentosPossiveis(np.array([[5, 3, 2], [6, 1, 8], [7, 0, 4]])))

In [ ]:
def fazerMovimento(tabela, movimento):
        # Faz um movimento no tabuleiro
        linha_zero, coluna_zero = buscaCoordenadas(tabela)
        novaTabela = tabela.copy()
        if movimento == (0,1):
            novaTabela[linha_zero, coluna_zero], novaTabela[linha_zero - 1, coluna_zero] = (
                novaTabela[linha_zero - 1, coluna_zero],
                novaTabela[linha_zero, coluna_zero],
            )
        elif movimento == (0,-1):
            novaTabela[linha_zero, coluna_zero], novaTabela[linha_zero + 1, coluna_zero] = (
                novaTabela[linha_zero + 1, coluna_zero],
                novaTabela[linha_zero, coluna_zero],
            )
        elif movimento == (-1,0):
            novaTabela[linha_zero, coluna_zero], novaTabela[linha_zero, coluna_zero - 1] = (
                novaTabela[linha_zero, coluna_zero - 1],
                novaTabela[linha_zero, coluna_zero],
            )
        elif movimento == (1,0):
            novaTabela[linha_zero, coluna_zero], novaTabela[linha_zero, coluna_zero + 1] = (
                novaTabela[linha_zero, coluna_zero + 1],
                novaTabela[linha_zero, coluna_zero],
            )
        return novaTabela

print(fazerMovimento(np.array([[5, 3, 2], [6, 1, 8], [7, 0, 4]]), (1, 0)))

In [ ]:
import numpy as np
def buscaCoordenadas(tabela,numero):
  # pegar as coordenadas do 0 (arrays)
  linha_zero,coluna_zero = np.where(tabela == numero)
  return linha_zero[0],coluna_zero[0]

def calculaManhattan(estadoAtual, estadoObjetivo, numero):
    distancia = 0
    coordenada_objetivo_linha, coordenada_objetivo_coluna = buscaCoordenadas(estadoObjetivo,numero)
    coordenada_atual_linha, coordenada_atual_coluna = buscaCoordenadas(estadoAtual,numero)
    distancia += abs(coordenada_atual_linha - coordenada_objetivo_linha) + abs(coordenada_atual_coluna - coordenada_objetivo_coluna)

    return distancia

estadoAtual = np.array([[5, 3, 2], [6, 1, 8], [7, 0, 4]])
estadoObjetivo = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 0]])
distancia = calculaManhattan(estadoAtual, estadoObjetivo,5)
print(f"A distância de Manhattan é {distancia}")