
# Exercícios com Numpy - Manipulação e Operações em Arrays

Este notebook é uma coleção de exercícios com a biblioteca Numpy, abordando manipulações e operações comuns em arrays.

## Conteúdos:
1. Criação e Manipulação de Arrays
2. Operações Matemáticas com Numpy
3. Exercícios para Prática de Fundamentos


### Exercícios NumPy

In [1]:
import numpy as np

**1.** Crie um array com 6 elementos em que os elementos possuem o padrão a seguir:

```
[0 2 4 6 8 10]
```

In [2]:
ex1_array = np.arange(0, 12, 2)
ex1_array

array([ 0,  2,  4,  6,  8, 10])

**2.** Crie um array $3 \times 4$ com o seguinte padrão:

```
[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]
 ```

In [3]:
ex2_array = np.array([[i ** 2 for i in range(j, j + 4)] for j in [0, 4, 9]])
ex2_array

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 81, 100, 121, 144]])

**3.** Crie um array $7\times7$ no qual todos os elementos têm valor 0, exceto os da linha 3 e da coluna 3, que têm valor 1, como a seguir:

```
[[0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [1 1 1 1 1 1 1]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]
 [0 0 0 1 0 0 0]]
```

In [4]:
ex3_array = np.zeros((7, 7), dtype=int)
ex3_array[:, 3] = 1
ex3_array[3, :] = 1
ex3_array

array([[0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0]])

**4.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[10  0  0  0  0]
 [ 0 10  0  0  0]
 [ 0  0 10  0  0]
 [ 0  0  0 10  0]
 [ 0  0  0  0 10]]
```

In [5]:
ex4_array = np.eye(5, dtype=int) * 10
ex4_array

array([[10,  0,  0,  0,  0],
       [ 0, 10,  0,  0,  0],
       [ 0,  0, 10,  0,  0],
       [ 0,  0,  0, 10,  0],
       [ 0,  0,  0,  0, 10]])

**5.** Crie um array $5 \times 5$ com o seguinte padrão:

```
[[ 1  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  9  0  0]
 [ 0  0  0 16  0]
 [ 0  0  0  0 25]]
```

Utilize as funções `np.diag` e `np.arange`.

In [6]:
diagonal_values = np.arange(1, 6) ** 2
ex5_array = np.diag(diagonal_values)
ex5_array

array([[ 1,  0,  0,  0,  0],
       [ 0,  4,  0,  0,  0],
       [ 0,  0,  9,  0,  0],
       [ 0,  0,  0, 16,  0],
       [ 0,  0,  0,  0, 25]])

**6.** Crie um array $3\times2\times4$ onde o elemento de índice $(i, j, k)$ tem valor $i^2$ para qualquer $j, k$, como abaixo:

```
[[[0 0 0 0]
  [0 0 0 0]]

 [[1 1 1 1]
  [1 1 1 1]]

 [[4 4 4 4]
  [4 4 4 4]]]
```

Dica: utilize a função `np.indices`.

In [7]:
i_indices = np.indices((3, 2, 4))[0]
ex6_array = i_indices ** 2
ex6_array


array([[[0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[4, 4, 4, 4],
        [4, 4, 4, 4]]])

**7.** Crie um array $5\times5$ onde o elemento de índice $(i,j)$ tem valor $i^2 + j^2$.

Dica: utilize a função `np.indices`.

In [8]:
i_indices, j_indices = np.indices((5, 5))
ex7_array = i_indices**2 + j_indices**2
ex7_array

array([[ 0,  1,  4,  9, 16],
       [ 1,  2,  5, 10, 17],
       [ 4,  5,  8, 13, 20],
       [ 9, 10, 13, 18, 25],
       [16, 17, 20, 25, 32]])

**8.** Gere uma matriz $10\times10$ de números aleatórios com distribuição normal de média 0 e desvio padrão 1. Calcule o *máximo* valor em cada linha e o *mínimo* valor em cada coluna.

Dica: utilize a função `np.randn`.

In [9]:
ex8_matrix = np.random.randn(10, 10)
ex8_matrix

array([[-2.10565859,  0.93485917, -0.49041113, -0.29609467, -0.95335288,
        -1.10129075,  0.8420209 ,  0.53523429,  1.44496031,  0.26181919],
       [-0.0833899 , -0.38838685,  1.04653632, -0.06411032,  0.58319575,
         1.15184189, -1.01893877, -0.91716786, -0.19192777, -0.84366795],
       [ 1.1593146 ,  0.2315824 , -0.98933918, -2.91161542, -0.35809267,
         1.40880299,  0.95298339, -0.49313647,  0.11730623,  0.246724  ],
       [-0.58459846, -0.02305089,  0.13159829,  0.0512717 ,  1.41782712,
         0.23632059,  1.22463236,  1.15648955, -0.47915947, -0.56606454],
       [ 1.19548348,  0.39088623,  1.59585305, -1.33268758, -0.20638994,
         1.17639987, -0.17918573, -0.53977631, -1.03861429,  1.95446934],
       [ 0.75555037,  0.92043581, -0.82823553,  1.40821688,  0.75270642,
         0.86809957, -2.18722004,  0.28612822,  1.20813513,  0.11254437],
       [ 0.21004357, -1.53650544, -0.34385974,  0.42422108, -0.56610596,
         0.30833016,  1.71948363, -0.86531813

In [10]:
max_per_row = np.max(ex8_matrix, axis=1)
max_per_row

array([1.44496031, 1.15184189, 1.40880299, 1.41782712, 1.95446934,
       1.40821688, 1.71948363, 0.86842669, 1.95202187, 2.34847846])

In [11]:
min_per_column = np.min(ex8_matrix, axis=0)
min_per_column

array([-2.10565859, -1.53650544, -0.98933918, -2.91161542, -0.95335288,
       -1.18042217, -2.18722004, -0.91716786, -2.07497487, -1.04986502])

**9.** Gere uma matriz $X \in \mathbb{R}^{5\times5}$ de números aleatórios com distribuição normal de média 1 e desvio padrão 3, isto é, $X \sim \text{N}(1, 3)$. Depois gere uma matriz $Y$ de mesmo formato cujo elemento $(i,j)$ terá valor $1$ se o elemento $(i,j)$ da matriz aleatória for menor que -5 ou maior do que 7, e zero caso contrário.
Conte o número de valores diferentes de zero nessa nova matriz.

Dica: se $X \sim \text{N}(0, 1)$, então $(\sigma \cdot X + \mu) \sim \text{N}(\mu, \sigma)$.

In [12]:
X = 3 * np.random.randn(5, 5) + 1
X

array([[-1.73260737,  0.45416699, -0.72050393,  4.70543629,  1.74431036],
       [ 5.76475025,  1.95207545,  0.94624303,  3.40989536,  3.60017979],
       [-5.36322109, -4.70001713,  3.86613152,  4.1863554 ,  2.52448002],
       [-1.59732577,  0.62949655,  3.21986152, -5.21427478, -1.76367645],
       [ 2.16810776,  2.57417106,  1.89596482,  4.1341505 ,  1.57298257]])

In [13]:
Y = np.where((X < -5) | (X > 7), 1, 0)
Y

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [14]:
non_zero_count = np.count_nonzero(Y)
non_zero_count

2

**10.** Use as regras de *broadcast* em seu benefício para gerar uma matriz $5\times5$ cujos elementos $(i,j)$ têm valor $i$. Faça o mesmo para gerar uma outra matriz de mesmo tamanho cujos elementos $(i,j)$ tenham valor $j$. Por fim, combine isso para gerar uma matriz também $5\times5$ cujos elementos $(i,j)$ tenham valor $2 i - j$.

Atenção: não utilizar `np.indices`.
Dica: utilizar soma com matriz de zeros com dimensões $10\times10$

In [15]:
i_values = np.arange(5).reshape(5, 1).astype(float)
i_matrix = i_values + np.zeros((5, 5))
i_matrix

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [16]:
j_values = np.arange(5).reshape(1, 5).astype(float)
j_matrix = np.zeros((5, 5)) + j_values
j_matrix

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

In [17]:
ex10_matrix= 2 * i_matrix - j_matrix
ex10_matrix

array([[ 0., -1., -2., -3., -4.],
       [ 2.,  1.,  0., -1., -2.],
       [ 4.,  3.,  2.,  1.,  0.],
       [ 6.,  5.,  4.,  3.,  2.],
       [ 8.,  7.,  6.,  5.,  4.]])

**11.** Considere a matriz

$
X = \begin{bmatrix}
  9 & 3 & 8 \\
  7 & 4 & 5 \\
  2 & 3 & 1 \\
  2 & 10 & 9 \\
  8 & 9 & 2 \\
\end{bmatrix}.
$

Calcule $X_{shifted} = X - \mu$, onde $\mu$ é a média das linhas de $X$. Explore a funcionalidade de broadcasting e não utilize loops.


In [18]:
X = np.array([[9, 3, 8], [7, 4, 5], [2, 3, 1], [2, 10, 9], [8, 9, 2]])

mu = X.mean(axis=1, keepdims=True)
mu_col = X.mean(axis=0, keepdims=True)

X_shifted = X - mu
Y_shifted = X - mu_col
ans = np.array([[3.4, -2.8, 3.0], [1.4, -1.8, 0.0], [-3.6, -2.8, -4.0], [-3.6, 4.2, 4.0], [2.4, 3.2, -3.0]])

are_equal = np.allclose(X_shifted, ans, atol=1e-5)
are_equal_y = np.allclose(Y_shifted, ans, atol=1e-5)

if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

if are_equal_y:
    print("Your function is correct.")
else:
    print("Your function is not correct.")
print("X_shifted:\n", X_shifted)
print("X_shifted:\n", Y_shifted)


Your function is not correct.
Your function is correct.
X_shifted:
 [[ 2.33333333 -3.66666667  1.33333333]
 [ 1.66666667 -1.33333333 -0.33333333]
 [ 0.          1.         -1.        ]
 [-5.          3.          2.        ]
 [ 1.66666667  2.66666667 -4.33333333]]
X_shifted:
 [[ 3.4 -2.8  3. ]
 [ 1.4 -1.8  0. ]
 [-3.6 -2.8 -4. ]
 [-3.6  4.2  4. ]
 [ 2.4  3.2 -3. ]]


**12.** A distância euclidiana entre dois vetores $u$ e $v$ de tamanho $n$ é dada por $\left\|u - v\right\|_2 = \sqrt{\sum_{i=1}^{n}(u_i - v_i)^2}.$

Dado os vetores (1-D arrays) a seguir, complete a função `euclidean_distance` para cálculo da distância. Não utilize loops, nem a função `np.linalg.norm`.

In [19]:
def euclidean_distance(u, v):
    distances = 0

    diff = u - v
    squared_diff = diff ** 2
    distances = np.sqrt(np.sum(squared_diff))

    return distances


array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

distances = euclidean_distance(array1, array2)
are_equal = np.allclose(distances, np.linalg.norm(array1 - array2), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

distances

Your function is correct.


5.196152422706632

**13.** Considere duas matrizes $X$ e $Y$, onde cada linha representa um vetor. Você foi solicitado a calcular a distância euclidiana entre as linhas de $X$ e as linhas correspondentes de $Y$. Escreva uma função que recebe as matrizes $X$ e $Y$ como entrada e retorna uma matriz $D$ onde cada elemento $(i,j)$ representa a distância euclidiana entre a linha $i$ de $X$ ($X_i$) e a linha $j$ de $Y$ ($Y_j$). O cálculo deve ser feito por meio de dois loops, conforme a equação

$D_{ij} = \left \|X_i - Y_j \right \|_2$

In [20]:
from scipy.spatial.distance import cdist


def calculate_distances_two_loops(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))

    for i in range(X.shape[0]):
        for j in range(Y.shape[0]):
            distances[i, j] = np.sqrt(np.sum((X[i] - Y[j]) ** 2))

    return distances


X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

distances = calculate_distances_two_loops(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**14.** O mesmo da questão anterior, mas agora utilizando um loop e broadcasting.

Dica: verifique se o resultado de `X[i] - Y` pode lhe ser útil na solução do exercício.

In [21]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

i = 2
print(X[i] - Y)

[[ -9  -9  -9]
 [-12 -12 -12]]


In [22]:
def calculate_distances_one_loop(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))

    for i in range(X.shape[0]):
        distances[i] = np.sqrt(np.sum((X[i] - Y) ** 2, axis=1))

    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.


**15.** O mesmo da questão anterior, mas agora - você que é um mago do broadcasting - não pode utilizar loops.

Dica: verifique se o resultado de `X[:, np.newaxis, :] - Y` pode lhe ser útil na solução do exercício.

In [23]:
# Create two 1D numpy array
X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15]])
Y = np.array([[16, 17, 18], [19, 20, 21]])

print(X[:, np.newaxis, :] - Y)

[[[-15 -15 -15]
  [-18 -18 -18]]

 [[-12 -12 -12]
  [-15 -15 -15]]

 [[ -9  -9  -9]
  [-12 -12 -12]]

 [[ -6  -6  -6]
  [ -9  -9  -9]]

 [[ -3  -3  -3]
  [ -6  -6  -6]]]


In [24]:
def calculate_distances_vectorized(X, Y):
    distances = np.zeros((X.shape[0], Y.shape[0]))

    diff = X[:, np.newaxis, :] - Y
    distances = np.sqrt(np.sum(diff ** 2, axis=2))

    return distances


distances = calculate_distances_one_loop(X, Y)
are_equal = np.allclose(distances, cdist(X, Y), atol=1e-5)
if are_equal:
    print("Your function is correct.")
else:
    print("Your function is not correct.")

Your function is correct.
